# export_fno_aot.py
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
import torch
import torch_mlir


from stfno.stfno_2d import FNO2d_global

# --- 1. MOCK CONFIGURATION ---

S = 64
modes = 12
width = 20
T_in = 1
T_out = 1
# Assuming 1 input parameter channel for this compile test
total_vector_a_elements_i = 1
total_vector_u_elements_i = 1
number_of_layers = 4

# Mocking the parameter order lists usually generated by NIMROD_pde...
input_parameter_order = [[0]]
mWidth_input_parameters = [1]
nWidth_output_parameters = [1]

# --- 2. INSTANTIATE MODEL ---
print("Instantiating Model...")
model = FNO2d_global(
    modes1=modes,
    modes2=modes,
    width=width,
    T_in=T_in,
    total_vector_a_elements_i=total_vector_a_elements_i,
    T=T_out,
    total_vector_u_elements_i=total_vector_u_elements_i,
    number_of_layers=number_of_layers,
    input_parameter_order0=input_parameter_order,
    mWidth_input_parameters0=mWidth_input_parameters,
    nWidth_output_parameters0=nWidth_output_parameters,
    if_model_jit_torchCompile=True,
)

model.eval()

# --- 3. CREATE DUMMY INPUT ---
batch_size = 1
input_channels = (
    T_in * total_vector_a_elements_i
) + 2  # +2 often for grid (x,y) or params
dummy_input = torch.randn(batch_size, S, S, input_channels)

print(f"Input Shape: {dummy_input.shape}")

# --- 4. COMPILE TO MLIR ---
print("Compiling to MLIR (Linalg on Tensors)...")
module = torch_mlir.compile(
    model, inputs=[dummy_input], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS
)

# --- 5. SAVE ---
mlir_filename = "stfno.mlir"
with open(mlir_filename, "w") as f:
    f.write(str(module))

print(f"Success! Saved {mlir_filename}")
print(f"You can now run 'iree-compile' on this file.")
